version: '3'

services:
  app-chat:
    build:
      context: ./.docker
      dockerfile: Dockerfile
    image: app-chat-node
    container_name: app-chat
    restart: unless-stopped
    volumes:
      - ./:/var/www/nodejs
    networks:
      - app-chat-networks

  webserver-chat:
    image: nginx:alpine
    container_name: webserver-chat
    restart: unless-stopped
    dns: 8.8.8.8
    ports:
      - "30021:80"
      - "3302:443"
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-chat-networks
          #MySQL Service
  db-chat:
    image: mysql:5.7.22
    container_name: db-chat
    restart: unless-stopped
    ports:
        - "33010:3306"
    environment: # tham số cấu hình MySQL
        MYSQL_DATABASE: app-chat
        MYSQL_ROOT_PASSWORD: 123123
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --max-allowed-packet=15000000
    volumes:
        - dbdata:/var/lib/mysql/
        - ./.docker/mysql/mysql.cnf:/etc/mysql/my.cnf
    networks:
        - app-chat-networks

networks:
  app-chat-networks:
    driver: bridge
#Volumes
volumes:
  dbdata:
      driver: local

