version: '3'

services:
  app-chat:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-chat-node
    container_name: app-chat
    restart: unless-stopped
    volumes:
      - ./:/var/www/nodejs
      - node_modules:/var/www/nodejs/node_modules
    networks:
      - app-chat-networks

  webserver-chat:
      image: nginx:alpine
      container_name: webserver-chat
      restart: unless-stopped
      dns: 8.8.8.8
      ports:
          - "30021:80"
          - "3302:443"
      volumes:
          - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      networks:
          - app-chat-networks
networks:
  app-chat-networks:
    driver: bridge
volumes:
  node_modules:

